# Course Syllabus {}

## Class and Instructor Details

MATH 550-901 (3 credits)

Virgil U. Pierce <br>
Email: virgil.pierce@unco.edu <br>
Cell: 956-249-0566

Office: Ross Hall 2239

Class Meetings:  

* 6/14 - 6/17: MTWR 1:00p - 4:00p
* 6/21 - 7/25: MW 1:00p - 4:00p

## No Textbook Purchase Required

Extensive notes for class will be distributed along with links to websites and other sources of information for the class.

## Course Description and Prerequisites

From the catalog: Methods related to descriptive and inferential statistics and the concept of probability are investigated in depth. 

Questions you will explore this summer:

* What is statistics and what are data?
* What is randomness and how do we describe long-run behavior?
* How do we describe our data?
* How do we make decisions from data?
* How do we use more data to update our decisions?
* Can we use these ideas to do computations in other areas of mathematics?

## Programing

Statistics is best experienced through doing the work rather than concentrating on theory and as such we need to use software for the course to do the necessary computations. This course will serve as an introduction to the statistics software R, which is widely used for statistical computations. It is freely available, open source, and has an extensive collection of help online for it.

If you are new to programming, R is a great place to learn because most of the tasks we do will involve just a few lines of commands. No prior knowledge of programming is assumed.

The course materials are being written in R and are available in Github for you at this link: https://github.com/virgilpierce/MATH_550

From there you can download individual files from the class or the entire course as a Zip file. Updates will be pushed to that site as they are prepared.

To access R and the editing software I recommend for using R and RStudio, you have options:

1. You can download Rstudio including R for your Windows or Mac computer by going here: https://www.rstudio.com/products/rstudio/download/ <br>
Be sure to choose the free option - you will not need the paid versions.

2. If you do not want to or cannot install Rstudio on your computer (for example if you are using a Tablet or Chromebook) you can use cocalc to run R commands: https://cocalc.com

3. You can log in to the Apporto Virtual Server https://unco.apporto.com/ with your UNC credentials and run Rstudio there.

## Course Pre-requisites

Students are expected to have experience with Calculus 1 and 2, however we will use Wolfram Alpha for any and all calculus computations so it is more the concepts of Derivative - as slope or rate of change; Integral - as area or volume; and the Fundamental Theorem of Calculus that connects these two ideas.

## Course Goals

1. Students will develop ways of thinking about data that will guide them as critical consumers of statistics in 2021 and beyond.
2. Students will develop coherent meanings for specific statistical concepts (and mathematical concepts) so that the use of the statistics becomes useful in their academic, professional, and personal lives.
3. Students will improve their problem-solving abilities.
4. Students will make logical and verbal arguments in support of their conclusions.

## Course Structure

Class will be a mixture of class discussion and group work. If you have been in my classes before it will be a familiar format. We will use Google Docs to collaborate during class, but you may be asked to share your screen to show the computation in R that you are doing.

You will need to be current on the homework for class in order to participate effectively in class. Collected work will be based on the discussion from class.

## Our compact with each other

Our agreement is:

1. Speak with Meaning - reference the attributes and using names for quantities and qualities (and people).

2. Exhibit Intellectual Integrity - base your conjecture on a logical foundation; do not pretend to an understanding. We are all still learning, and admitting that is an important step forward.

3. Strive to Make Sense - persist in making sense of your peer's thinking. Almost every problem we do in class has a variety of approaches and a variety of answers.

4. Respect the Learning Process of All - allow others time to think, reflect, and construct. Pose questions of others.

## Assignments

1. Projects: There will be two take home projects and a final project. You will have at least five days to complete these. They will be partly computational, and partly reflective. They will also have components that are unique to each individual. They are open notes, and in particular any resource online about using R is available provided it is not in the format of a Q&A. If at all in doubt about a resource you have found, please ask. All resources used should be cited. 

2. Homework:  The homework is posed with the intent that you will collaborate with others on it, and you are encouraged to do so. Your instructor is available during the week to consult with as well.

3. Questions: You will occasionally be asked to compose a question for others in the class. These assignments will be collected during class. You will provide your question with a description of how it should be solved (from your point of view) and how it addresses the goal or concept.

4. Evidence of Learning: Your grade in the class is going to be based on your progress towards answering the questions posed in the Course Description. Evidence will naturally come from your submissions for the three types of assignments above, however you are encouraged to consider other evidence that could be provided.

## Grades

Your grade will be based upon the 4 assignment types above and the extent to which they contain evidence that the course goals have been met. Exceeding expectations on all four course goals will result in a grade of A; a grade of B will mean that all of the course goals were met and on at least one the expectation was exceeded; a grade of C will mean that all of the course goals were met; a grade of D will mean that some of the course goals were met but not all of them; and a grade of F will mean that none of the course goals were met.

## UNCO Policy Statements

### Disability Resources

It is the policy and practice of the University of Nothern Colorado to create inclusive learning environments - including this class. If there are aspects of the instruction or design of this course that present barriers to your inclusion or to an accurate assessment of your achievement [learning] such as time-limited exams, inaccessible web content, or use of videos without captions, please communicate this with your professor and contact Disability Support Services (DSS) at (970) 351-2289, Michener Library L-80 to request accommodations. Students can learn more about the accomodation process at https://www.unco.edu/disability-resource-center/accomodations/

### Food Insecurity and Basic Needs

Research shows that college students experience food insecurity at higher rates than the American household rate, and that food insecurity can negatively impact academic performance and persistence. In recognition of this problem, UNC offers assistance to students facing food insecurity through an on-campus food pantry. *The Bear Pantry*  
is located in University Center 2166A, and is open for regular hours throughout the semester. 

Please visit http://www.unco.edu/bear-pantry for more information.

Any student who faces challenges securing their food or housing and believes this may affect their performance in the course is also urged to contact Student Outreach and Support (SOS) for assistance. SOS can assist students during difficult circumstances which may include medical, mental health, personal or family crisis, illness or injury. SOS can be reached at sos@unco.edu or via phone at 970-351-2796.

### Honor Code

All members of the Univeristy of Northern Colorado community are entrustred with the responsibility to uphold and promote five fundamental values: Honesty, Trust, Respect, Fairness, and Responsibility. These core elements foster an atmosphere, insite and outside the classroom, which serves as a foundation and guides the UNC community's academic, professional, and personal growth. Endorsement of these core elements by students, faculty, staff, administration, and trustees strengthens the integrity and value of our academic climate. 

### UNC's Policies

There are more university policies not printed here, but published in the course catalog, university regulations, and the UNC Board of Trustees Policy Manual. In particular we will follow UNC's polices and recomendations for academic misconduct. For additional information, please see the Student Code of Conduct at the Dean of Student's website: http://wwww.unco.edu/dos/Conduct/codeofconduct.html. In the case of academic appeals, university procedures will be followed. For information on academic appeals see: https://www.unco.edu/trustees/pdf/board-policy-manual.pdf.
